// src/context/LanguageContext.js
import React, { createContext, useContext, useState } from 'react';

const translations = {
  mr: {
    // Navbar
    home: 'मुखपृष्ठ',
    about: 'आमच्याबद्दल',
    gallery: 'दालन',
    blog: 'ब्लॉग',
    grampanchayat: 'ग्रामपंचायत',
    contact: 'संपर्क',
    admin: 'प्रशासन',

    // Hero
    welcome: 'आपले सांगवडेवाडी गावात स्वागत आहे',
    subtitle: 'करवीर तालुका • कोल्हापूर जिल्हा • महाराष्ट्र',
    heroBtn1: 'गावाबद्दल जाणून घ्या',
    heroBtn2: 'दालन पहा',

    // About
    aboutTitle: 'आमच्या गावाबद्दल',
    aboutText: 'सांगवडेवाडी हे कोल्हापूर जिल्ह्यातील करवीर तालुक्यात वसलेले एक सुंदर गाव आहे. लोकसंख्या सुमारे ४००० असलेले हे गाव आपल्या समृद्ध संस्कृती, हिरव्यागार निसर्गसौंदर्य आणि एकोप्याने जगणाऱ्या समाजासाठी ओळखले जाते.',
    readMore: 'अधिक वाचा',
    population: 'लोकसंख्या',
    pinCode: 'पिन कोड',
    taluka: 'तालुका',
    district: 'जिल्हा',

    // Gallery
    galleryTitle: 'छायाचित्र दालन',
    gallerySubtitle: 'आमच्या गावाचे सुंदर क्षण',
    all: 'सर्व',
    festivals: 'उत्सव',
    nature: 'निसर्ग',
    events: 'कार्यक्रम',
    people: 'लोक',
    viewAll: 'सर्व पहा',

    // Blog
    blogTitle: 'ताज्या बातम्या',
    blogSubtitle: 'गावातील घडामोडी',
    readPost: 'पूर्ण वाचा',
    categories: 'श्रेणी',
    news: 'बातम्या',
    stories: 'कथा',

    // Today in Village
    todayTitle: 'आज गावात',
    todaySubtitle: 'ताज्या घडामोडी आणि सूचना',
    noUpdates: 'सध्या कोणत्याही नवीन घडामोडी नाहीत',

    // Awards
    awardsTitle: 'पुरस्कार आणि उपलब्धी',
    awardsSubtitle: 'आमच्या गावाचा गौरव',

    // Grampanchayat
    gpTitle: 'ग्रामपंचायत',
    gpSubtitle: 'आमचे लोकप्रतिनिधी',
    sarpanch: 'सरपंच',
    member: 'सदस्य',
    notices: 'सूचना आणि जाहीरनामे',

    // Contact
    contactTitle: 'संपर्क करा',
    contactSubtitle: 'आम्हाला लिहा किंवा भेट द्या',
    name: 'नाव',
    email: 'ईमेल',
    message: 'संदेश',
    send: 'पाठवा',
    address: 'पत्ता',
    phone: 'दूरध्वनी',
    messageSent: 'संदेश यशस्वीरित्या पाठवला!',

    // Footer
    footerTagline: 'एकता, प्रगती आणि संस्कृती',
    quickLinks: 'जलद दुवे',
    followUs: 'आम्हाला फॉलो करा',
    allRights: 'सर्व हक्क राखीव',

    // Admin
    adminTitle: 'प्रशासन पॅनेल',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    dashboard: 'डॅशबोर्ड',
    manageBlogs: 'ब्लॉग व्यवस्थापन',
    manageGallery: 'दालन व्यवस्थापन',
    manageAwards: 'पुरस्कार व्यवस्थापन',
    manageGP: 'ग्रामपंचायत व्यवस्थापन',
    manageTodayUpdates: 'आजच्या घडामोडी',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'हटवा',
    edit: 'संपादित करा',
    add: 'जोडा',
    title: 'शीर्षक',
    description: 'वर्णन',
    image: 'प्रतिमा',
    upload: 'अपलोड करा',
    password: 'पासवर्ड',
    loading: 'लोड होत आहे...',
  },
  hi: {
    home: 'मुख्य पृष्ठ',
    about: 'हमारे बारे में',
    gallery: 'गैलरी',
    blog: 'ब्लॉग',
    grampanchayat: 'ग्रामपंचायत',
    contact: 'संपर्क',
    admin: 'प्रशासन',
    welcome: 'सांगवडेवाडी गाँव में आपका स्वागत है',
    subtitle: 'करवीर तालुका • कोल्हापुर जिला • महाराष्ट्र',
    heroBtn1: 'गाँव के बारे में जानें',
    heroBtn2: 'गैलरी देखें',
    aboutTitle: 'हमारे गाँव के बारे में',
    aboutText: 'सांगवडेवाडी कोल्हापुर जिले के करवीर तालुका में स्थित एक सुंदर गाँव है। लगभग ४000 की आबादी वाला यह गाँव अपनी समृद्ध संस्कृति, हरे-भरे प्राकृतिक सौंदर्य और एकजुट समाज के लिए जाना जाता है।',
    readMore: 'और पढ़ें',
    population: 'जनसंख्या',
    pinCode: 'पिन कोड',
    taluka: 'तालुका',
    district: 'जिला',
    galleryTitle: 'फोटो गैलरी',
    gallerySubtitle: 'हमारे गाँव के सुंदर पल',
    all: 'सभी',
    festivals: 'त्योहार',
    nature: 'प्रकृति',
    events: 'कार्यक्रम',
    people: 'लोग',
    viewAll: 'सभी देखें',
    blogTitle: 'ताज़ा समाचार',
    blogSubtitle: 'गाँव की गतिविधियाँ',
    readPost: 'पूरा पढ़ें',
    categories: 'श्रेणियाँ',
    news: 'समाचार',
    stories: 'कहानियाँ',
    todayTitle: 'आज गाँव में',
    todaySubtitle: 'ताज़ी गतिविधियाँ और सूचनाएं',
    noUpdates: 'अभी कोई नई गतिविधि नहीं है',
    awardsTitle: 'पुरस्कार और उपलब्धियाँ',
    awardsSubtitle: 'हमारे गाँव का गौरव',
    gpTitle: 'ग्रामपंचायत',
    gpSubtitle: 'हमारे जनप्रतिनिधि',
    sarpanch: 'सरपंच',
    member: 'सदस्य',
    notices: 'सूचनाएं और अधिसूचनाएं',
    contactTitle: 'संपर्क करें',
    contactSubtitle: 'हमें लिखें या मिलने आएं',
    name: 'नाम',
    email: 'ईमेल',
    message: 'संदेश',
    send: 'भेजें',
    address: 'पता',
    phone: 'फोन',
    messageSent: 'संदेश सफलतापूर्वक भेजा गया!',
    footerTagline: 'एकता, प्रगति और संस्कृति',
    quickLinks: 'त्वरित लिंक',
    followUs: 'हमें फॉलो करें',
    allRights: 'सर्वाधिकार सुरक्षित',
    adminTitle: 'प्रशासन पैनल',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    dashboard: 'डैशबोर्ड',
    manageBlogs: 'ब्लॉग प्रबंधन',
    manageGallery: 'गैलरी प्रबंधन',
    manageAwards: 'पुरस्कार प्रबंधन',
    manageGP: 'ग्रामपंचायत प्रबंधन',
    manageTodayUpdates: 'आज की गतिविधियाँ',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    title: 'शीर्षक',
    description: 'विवरण',
    image: 'छवि',
    upload: 'अपलोड करें',
    password: 'पासवर्ड',
    loading: 'लोड हो रहा है...',
  },
  en: {
    home: 'Home',
    about: 'About',
    gallery: 'Gallery',
    blog: 'Blog',
    grampanchayat: 'Grampanchayat',
    contact: 'Contact',
    admin: 'Admin',
    welcome: 'Welcome to Sangwadewadi Village',
    subtitle: 'Karvir Taluka • Kolhapur District • Maharashtra',
    heroBtn1: 'Explore Village',
    heroBtn2: 'View Gallery',
    aboutTitle: 'About Our Village',
    aboutText: 'Sangwadewadi is a beautiful village located in Karvir Taluka of Kolhapur District. With a population of approximately 4000, this village is known for its rich culture, lush natural beauty, and a united community.',
    readMore: 'Read More',
    population: 'Population',
    pinCode: 'Pin Code',
    taluka: 'Taluka',
    district: 'District',
    galleryTitle: 'Photo Gallery',
    gallerySubtitle: 'Beautiful Moments of Our Village',
    all: 'All',
    festivals: 'Festivals',
    nature: 'Nature',
    events: 'Events',
    people: 'People',
    viewAll: 'View All',
    blogTitle: 'Latest News',
    blogSubtitle: 'Village Activities',
    readPost: 'Read Post',
    categories: 'Categories',
    news: 'News',
    stories: 'Stories',
    todayTitle: "Today in Village",
    todaySubtitle: 'Latest Updates & Announcements',
    noUpdates: 'No new updates at the moment',
    awardsTitle: 'Awards & Achievements',
    awardsSubtitle: 'Pride of Our Village',
    gpTitle: 'Grampanchayat',
    gpSubtitle: 'Our Representatives',
    sarpanch: 'Sarpanch',
    member: 'Member',
    notices: 'Notices & Announcements',
    contactTitle: 'Contact Us',
    contactSubtitle: 'Write to Us or Visit',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    send: 'Send',
    address: 'Address',
    phone: 'Phone',
    messageSent: 'Message sent successfully!',
    footerTagline: 'Unity, Progress & Culture',
    quickLinks: 'Quick Links',
    followUs: 'Follow Us',
    allRights: 'All Rights Reserved',
    adminTitle: 'Admin Panel',
    login: 'Login',
    logout: 'Logout',
    dashboard: 'Dashboard',
    manageBlogs: 'Manage Blogs',
    manageGallery: 'Manage Gallery',
    manageAwards: 'Manage Awards',
    manageGP: 'Manage Grampanchayat',
    manageTodayUpdates: "Today's Updates",
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    title: 'Title',
    description: 'Description',
    image: 'Image',
    upload: 'Upload',
    password: 'Password',
    loading: 'Loading...',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('mr');
  const t = (key) => translations[language]?.[key] || translations['mr'][key] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
